# Generated by Django 4.1.7 on 2023-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_fuel_currency_stationfuel_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stationfuel",
            name="fuel",
        ),
        migrations.AddField(
            model_name="stationfuel",
            name="icon",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="stationfuel",
            name="name",
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name="Fuel",
        ),
    ]
